### ISSUE TITLE
Lỗi khi request vượt quá số token tối đa

### ISSUE THREAD

**Issue by brevisnguyen** [monokaijs/chatgpt-bot-nodejs#1]
" This model’s maximum context length is 4097 tokens,...."

Bạn có thể xử lý cắt nhỏ token và hợp nhất kết quả khi trả về không ạ?

**Comment by monokaijs** [comment]
Trong DbService, mình có làm một cái để clear tin nhắn, bạn có thể tạo lệnh Telegram để clear mỗi khi bị exceed.
Hiện tại mình vẫn đang nghiên cứu, cơ mà để cải thiện được thì chắc phải ngâm khá lâu

**Comment by brevisnguyen** [comment]
Cảm ơn bạn, mình sẽ ngâm cứu
